DROP DATABASE if exists Sasa;

CREATE DATABASE IF NOT exists Sasa DEFAULT CHARACTER SET UTF8MB4 DEFAULT COLLATE utf8mb4_general_ci;
USE Sasa;
CREATE TABLE IF NOT EXISTS Clientes (
    id INT AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    cuit BIGINT,
    PRIMARY KEY (id)
) ENGINE=INNODB;